language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer install --prefer-source --dev

script:
  - vendor/bin/phpunit
